# overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab

namePrefix: prod-

resources:
  - ../../base/movie-service

images:
  - name: movie-service
    newTag: v2

replicas:
  - name: movie-service
    count: 3