apiVersion: v1
kind: Pod
metadata:
  labels:
    run: movie-service-flags-demo
  name: movie-service-flags-demo
spec:
  containers:
  - image: movie-service:1.0.0
    name: movie-service-flags-demo
    resources: {}
    imagePullPolicy: IfNotPresent
    env:
      - name: DB_HOST
        value: postgres-movie.movie-booking.svc.cluster.local
      - name: DB_PORT
        value: "5432"
      - name: DB_NAME
        value: movie_service
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: movie-service-db-secret
            key: DB_PASSWORD
    volumeMounts:
      - name: feature-flags
        mountPath: /etc/movie-service/feature-flags
  volumes:
    - name: feature-flags
      configMap:
        name: movie-service-feature-flags
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
