apiVersion: v1
kind: Pod
metadata:
  name: movie-api-client
  namespace: lab

spec:
  serviceAccountName: movie-reader

  containers:
  - name: app
    image: movie-service:1.0.0
    imagePullPolicy: IfNotPresent

    command:
      - sleep
      - infinity
